#!/usr/bin/env python3


import rospy
from geometry_msgs.msg import Twist
from turtlesim.msg import Pose

rospy.init_node("kame")
pub = rospy.Publisher("/turtle1/cmd_vel", Twist, queue_size=10)
rate = rospy.Rate(10)
move = Twist()
pose = Pose()

def update_pose(data):
    global pose
    pose.x = data.x
    pose.y = data.y
    
while not rospy.is_shutdown() :
    move.linear.x = 1
    move.angular.z =0
    if   pose.x >= 10.00:
        move.linear.x  = 1
        move.angular.z = 3
        
    elif pose.x >= 1:
        move.linear.x  = 2
        move.angular.z = 1
 
    ### 縦座標設定
    if   pose.y < 0:
        move.linear.x  = 2
        move.angular.z = 1
    elif pose.y >= 10:
        move.linear.x  = 2
        move.angular.z = 1
    
    pub.publish(move)
    rate.sleep()